<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Chat.aspx.cs" Inherits="SignalRChat.Chat" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <link rel="shortcut icon" href="images/fevicon.png" type="image/x-icon" />

    <title>SignalR Chat : Chat Page</title>

    <link href="Content/bootstrap.css" rel="stylesheet" />
    <link href="Content/style.css" rel="stylesheet" />
    <link href="Content/jquery-confirm.min.css" rel="stylesheet" />
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />

    <script src="Scripts/jQuery-3.2.1.min.js"></script>
    <script src="Scripts/jquery.signalR-2.2.2.min.js"></script>
    <script src="Scripts/date.format.js"></script>

    <script src="https://cdn.tiny.cloud/1/lavcx8nf2ec5iq2bmbfq9q1pvrbx4q44mto3bt247td0kmum/tinymce/5/tinymce.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!--Jquery slimScroll -->
    <script type="text/javascript" src="Scripts/jquery.slimscroll.min.js"></script>
    <script src="Scripts/bootstrap.min.js"></script>
    <script src="Scripts/favico.js"></script>

    <script type="text/javascript">
        tinymce.init({
            selector: "textarea#txtMessage",
            menubar: false,
            plugins: "link image code emoticons",
            toolbar: 'undo redo | styleselect | forecolor | bold italic | alignleft aligncenter alignright alignjustify | outdent indent | link image | code | charmap emoticons',
            branding: false,
            setup: function (editor) {
                editor.on('keydown', function (e) {
                    if (e.keyCode == 13 && !e.shiftKey) {
                        e.preventDefault();
                        e.stopPropagation();
                        $('#btnSendMsg').click();
                    }
                });
            }
        });

        tinymce.init({
            selector: "textarea#txtEditMessage",
            menubar: false,
            plugins: "link image code emoticons",
            toolbar: 'undo redo | styleselect | forecolor | bold italic | alignleft aligncenter alignright alignjustify | outdent indent | link image | code | charmap emoticons',
            branding: false,
            setup: function (editor) {
                editor.on('keydown', function (e) {
                    if (e.keyCode == 13 && !e.shiftKey) {
                        e.preventDefault();
                        e.stopPropagation();
                        $('#btnEditSendMsg').click();
                    }
                });
            }
        });
    </script>
    <script type="text/javascript">

        var badge = 0;
        var favicon = new Favico({
            position: 'up',
            animation: 'popFade',
            bgColor: '#dd2c00',
            textColor: '#fff0e2'
        });

        var IntervalVal;
        var soundObject = null;
        $(function () {

            // Declare a proxy to reference the hub.
            $.connection.hub.logging = true;

            var chatHub = $.connection.chatHub;
            registerClientMethods(chatHub);
            // Start Hub
            $.connection.hub.start().done(function () {
                registerEvents(chatHub);
            });

            $.connection.hub.disconnected(function () {
                $.connection.hub.start().done(function () {
                    chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                });
            });
        });

        // Show Title Alert
        function ShowTitleAlert(newMessageTitle, pageTitle) {
            if (document.title == pageTitle) {
                document.title = newMessageTitle;
            }
            else {
                document.title = pageTitle;
            }
        }

        function registerEvents(chatHub) {

            var name = '<%# this.UserName %>';
            var userid = '<%# this.UserId %>';

            if (name.length > 0) {
                chatHub.server.connect(name, userid);
            }

            // Send Button Click Event
            $('#btnSendMsg').click(function () {
                var msg = tinymce.get("txtMessage").getContent();

                if (msg.length > 0) {

                    var toUserId = $('#ReceiverId').val();
                    var fromUserId = $('#SenderId').val();

                    if (chatHub.connection.state == 4) {
                        $.connection.hub.start().done(function () {
                            chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                            if ($("#GrpId").val()) {
                                chatHub.server.sendGroupMessage($("#GrpId").val(), $("#GrpName").val(), fromUserId, msg);
                            } else {
                                chatHub.server.sendPrivateMessage(toUserId, fromUserId, msg);
                            }
                        });
                    }
                    else {
                        if ($("#GrpId").val()) {
                            chatHub.server.sendGroupMessage($("#GrpId").val(), $("#GrpName").val(), fromUserId, msg);
                        } else {
                            chatHub.server.sendPrivateMessage(toUserId, fromUserId, msg);
                        }
                    }

                    $("#txtMessage").val('');
                    tinymce.get("txtMessage").setContent('');
                }
            });

            // Send Message on Enter Button
            $("#txtMessage").keypress(function (e) {
                if (event.keyCode == 13 && event.shiftKey) {
                    var content = this.value;
                    var caret = getCaret(this);
                    this.value = content.substring(0, caret) + "\n" + content.substring(caret, content.length - 1);
                    event.stopPropagation();
                }
                else if (e.which == 13) {
                    $('#btnSendMsg').click();
                    e.preventDefault();
                }
            });

            // Edit Msg Click Event
            $('#btnEditSendMsg').click(function () {
                var msg = tinymce.get("txtEditMessage").getContent();
                var MessageId = $(".EditMessageId").val();

                if (msg.length > 0) {

                    var toUserId = $('#ReceiverId').val();
                    var fromUserId = $('#SenderId').val();

                    if (chatHub.connection.state == 4) {
                        $.connection.hub.start().done(function () {
                            chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                            if ($("#GrpId").val()) {
                                chatHub.server.editGroupMessage($("#GrpId").val(), $("#GrpName").val(), fromUserId, msg, MessageId);
                            } else {
                                chatHub.server.editMessage(toUserId, fromUserId, msg, MessageId);
                            }
                        });
                    }
                    else {
                        if ($("#GrpId").val()) {
                            chatHub.server.editGroupMessage($("#GrpId").val(), $("#GrpName").val(), fromUserId, msg, MessageId);
                        } else {
                            chatHub.server.editMessage(toUserId, fromUserId, msg, MessageId);
                        }
                    }

                    $("#txtEditMessage").val('');
                    tinymce.get("txtEditMessage").setContent('');
                    $('#EditMessage').modal('hide');
                }
            });
        }

        function getCaret(el) {
            if (el.selectionStart) {
                return el.selectionStart;
            } else if (document.selection) {
                el.focus();
                var r = document.selection.createRange();
                if (r == null) {
                    return 0;
                }
                var re = el.createTextRange(),
                    rc = re.duplicate();
                re.moveToBookmark(r.getBookmark());
                rc.setEndPoint('EndToStart', re);
                return rc.text.length;
            }
            return 0;
        }

        function registerClientMethods(chatHub) {

            // Calls when new user connected
            chatHub.client.onNewUserConnected = function (userId, userName, UserImg, logintime) {
                $("#Div" + userId).find("i").removeClass("red").addClass("green");
            }

            // Calls when user disconnect
            chatHub.client.onUserDisconnected = function (userId, userName) {
                $("#Div" + userId).find("i").removeClass("green").addClass("red");
            }

            // Calls when user successfully logged in
            chatHub.client.onConnected = function (id, userName, allUsers, allGroups) {

                $('#SenderId').val(id);
                $('#ReceiverId').val(id);
                $('#SenderName').val(userName);
                $('#spanUser').html(userName);

                // Add Unread Msg Count to Fevicon Badeg
                var someArray = allUsers.map(x => x.IsRead);
                for (var i = 0; i < someArray.length; i++) {
                    badge += someArray[i] << 0;
                }

                badge = (badge < 0) ? 0 : (badge);
                favicon.badge(badge);

                // Add All Users
                for (i = 0; i < allUsers.length; i++) {
                    AddUser(allUsers[i].UserId, allUsers[i].UserName, allUsers[i].UserImage, allUsers[i].IsRead, allUsers[i].IsOnline, allUsers[i].RecentMsg, allUsers[i].RecentMsgTime, allUsers[i].IsPin);
                }

                chatHub.server.getPrivateMessage(id, id);
                //chatHub.server.getGroups(id);
                for (i = 0; i < allGroups.length; i++) {
                    AddGroup(allGroups[i].ID, allGroups[i].GroupName, allGroups[i].CreatedBy, allGroups[i].RecentMsg, allGroups[i].UserName);
                }

                var objDiv = document.getElementById("divChatWindow");
                objDiv.scrollTop = objDiv.scrollHeight;
            }

            chatHub.client.sendPrivateMessage = function (userId, fromUserName, message, userimg, CurrentDateTime, MessageId) {

                if ($('#SenderId').val() == userId || $('#ReceiverId').val() == userId) {
                    AddMessage(fromUserName, message, CurrentDateTime, userimg, MessageId);

                    var objDiv = document.getElementById("divChatWindow");
                    objDiv.scrollTop = objDiv.scrollHeight;
                }

                if ($(message).find("h4").html()) {
                    message = $(message).find("h4").html();
                }

                $("#Div" + userId).find(".RecentMsg").html($(message).text());
            }

            chatHub.client.GetPrivateMessage = function (messages) {

                // Add Existing Messages
                for (i = 0; i < messages.length; i++) {
                    AddMessage(messages[i].UserName, messages[i].Message, messages[i].Time, messages[i].UserImage, messages[i].MessageId, messages[i].IsRead, messages[i].IsEdited);
                }

                var objDiv = document.getElementById("divChatWindow");
                objDiv.scrollTop = objDiv.scrollHeight;
            }

            chatHub.client.sendNotification = function (userId, fromUserName, message, userimg, CurrentDateTime) {

                if ($('#ReceiverId').val() != userId) {
                    badge++;
                    badge = (badge < 0) ? 0 : (badge);
                    favicon.badge(badge);
                    $("#Div" + userId).find(".badge-count").each(function () {
                        var IsRead = parseInt($(this).find(".w3-badge").text());
                        if (isNaN(IsRead)) { IsRead = 0; }
                        IsRead++;
                        $(this).replaceWith('<a class="badge-count"><span class="w3-badge w3-red">' + IsRead + '</span></a>');
                    });
                    DesktopNotification(message);
                } else {

                    if (document.hidden) {
                        badge++;
                        badge = (badge < 0) ? 0 : (badge);
                        favicon.badge(badge);
                        $("#Div" + userId).find(".badge-count").each(function () {
                            var IsRead = parseInt($(this).find(".w3-badge").text());
                            if (isNaN(IsRead)) { IsRead = 0; }
                            IsRead++;
                            $(this).replaceWith('<a class="badge-count"><span class="w3-badge w3-red">' + IsRead + '</span></a>');
                        });
                        DesktopNotification(message);
                    }
                    else {
                        if (chatHub.connection.state == 4) {
                            $.connection.hub.start().done(function () {
                                chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                                chatHub.server.readMessage(userId, $("#SenderId").val());
                            });
                        } else
                            chatHub.server.readMessage(userId, $("#SenderId").val());
                    }
                }
                PlaySound();
            }

            chatHub.client.GetNotification = function (notifications, flag) {
                if (flag == 2)
                    $(".dropdown-toggle:eq(0)").dropdown('toggle');

                $('#notiContent').empty();

                if (notifications.length > 0) {
                    var count = notifications.filter(x => x.Is_Read == false).length;
                    if (count != 0) {
                        $('.badge-light').html(notifications.filter(x => x.Is_Read == false).length);
                    } else {
                        $('.badge-light').html('&nbsp;');
                    }
                } else {
                    $('#notiContent').append($('<li>No data available</li>'));
                    $('.badge-light').html('&nbsp;');
                }

                $.each(notifications, function (index, value) {
                    if (value.Is_Read != true) {
                        $('#notiContent').append($('<li class="unread-msg" onclick="changenoty(' + value.ID + ')">' + value.Notification + '</li>'));
                    }
                    else {
                        $('#notiContent').append($('<li class="read-msg">' + value.Notification + '</li>'));
                    }
                });
            }

            chatHub.client.sendEditedMessage = function (userId, fromUserName, message, userimg, CurrentDateTime, MessageId) {
                if ($('#SenderId').val() == userId || $('#ReceiverId').val() == userId) {
                    EditMessage(fromUserName, message, CurrentDateTime, userimg, MessageId);
                }
            }

            chatHub.client.sendDeletedMessage = function (MessageId) {
                $("#Msg" + MessageId).remove();
            }

            chatHub.client.GetGroups = function (groups) {
                for (i = 0; i < groups.length; i++) {
                    AddGroup(groups[i].ID, groups[i].GroupName, groups[i].CreatedBy);
                }
            }

            chatHub.client.AddToGroup = function (groupId, groupName, CreatedBy) {
                AddGroup(groupId, groupName, CreatedBy);
            }

            chatHub.client.sendGroupMessage = function (groupId, fromUserName, message, userimg, CurrentDateTime, MessageId) {
                AddMessage(fromUserName, message, CurrentDateTime, userimg, MessageId);

                var objDiv = document.getElementById("divChatWindow");
                objDiv.scrollTop = objDiv.scrollHeight;

                if ($(message).find("h4").html()) {
                    message = $(message).find("h4").html();
                }

                $("#Grp" + groupId).find(".RecentMsg").html(fromUserName + " " + $(message).text());
            }

            chatHub.client.sendEditedGroupMessage = function (userId, fromUserName, message, userimg, CurrentDateTime, MessageId) {
                EditMessage(fromUserName, message, CurrentDateTime, userimg, MessageId);
            }

            chatHub.client.sendDeletedGroup = function (groupId) {
                $("#Grp" + groupId).remove();

                if ($("#GrpId").val() == groupId) {
                    $('#GrpId').val('');
                    $('#GrpName').val('');

                    $('#ReceiverId').val($("#SenderId").val());
                    $('#spanUser').html($("#SenderName").val());
                    $('#ReceiverName').val($("#SenderName").val());

                    $('#divChatWindow').html('');

                    chatHub.server.getPrivateMessage($("#SenderId").val(), $("#SenderId").val());
                }
            }

            chatHub.client.sendEditedGroup = function (groupId, groupName, CreatedBy) {
                $("#Grp" + groupId).find("a.user").text(groupName);

                if ($("#GrpId").val() == groupId) {
                    $('#spanUser').html("# " + groupName);
                }
            }

            chatHub.client.sendGroupNotification = function (notification) {
                DesktopNotification(notification);
            }

            chatHub.client.getUsers = function (allUsers) {
                // Filter User List
                $("#divusers").html('');
                for (i = 0; i < allUsers.length; i++) {
                    AddUser(allUsers[i].UserId, allUsers[i].UserName, allUsers[i].UserImage, allUsers[i].IsRead, allUsers[i].IsOnline, allUsers[i].RecentMsg, allUsers[i].RecentMsgTime);
                }

                if ($("#myInput").val()) {
                    myFunction();
                }
            }

            chatHub.client.ReadMessage = function (UserId) {
                if ($('#ReceiverId').val() == UserId) {
                    $(".direct-chat-msg.right").find(".msgstatus").attr('src', '/images/doublegreen.png');
                }
            }
        }

        function GetCurrentDateTime(now) {

            var localdate = dateFormat(now, "dddd, mmmm dS, yyyy, h:MM:ss TT");

            return localdate;
        }

        function AddGroup(groupId, groupName, CreatedBy, RecentMsg, UserName) {
            var SenderId = $('#SenderId').val();
            var deletebtn = '';
            if (!RecentMsg) {
                RecentMsg = ''; UserName = '';
            } else if ($(RecentMsg).find("h4").html()) {
                RecentMsg = $(RecentMsg).find("h4").html();
            }

            if (SenderId == CreatedBy) {
                deletebtn = '<a onclick="OpenEditGroup(' + groupId + ')" class="btn btn-box-tool pull-right" data-toggle="tooltip" title="Edit Group"><i class="fa fa-pencil-square-o" ></i></a>' +
                    '<a onclick="DeleteGroup(' + groupId + ')" class="btn btn-box-tool pull-right" data-toggle="tooltip" title="Delete Group"><i class="fa fa-trash-o" ></i></a>'
            }

            var code = $('<div class="box-comment" id="Grp' + groupId + '">' +
                '<i class="fa fa-hashtag" aria-hidden="true"></i>' +
                '<div class="comment-text">' +
                '<span class="username">' + '<a onclick="OpenChatRoom(' + groupId + ',this)" id="' + groupId + '" class="user" >' + groupName + '</a>' + deletebtn + '</span>' +
                '<span class="RecentMsg">' + UserName + ' ' + $(RecentMsg).text() + '</span></div></div>');

            $("#divgroups").append(code);
        }

        function AddUser(userId, name, UserImage, IsRead, IsOnline, RecentMsg, RecentMsgTime, IsPin) {
            var SenderId = $('#SenderId').val();
            var Badge = '<a class="badge-count"></a>';
            var Status = '<i class="fa fa-circle red"></i>';
            var Pinstatus = IsPin == false ? '<img class="pinstatus" style="height: 15px !important;width: 15px !important;" src="/images/pin.png" />' : '<img class="pinstatus" style="height: 15px !important;width: 15px !important;" src="/images/unpin.png" />';

            if ($(RecentMsg).find("h4").html()) {
                RecentMsg = $(RecentMsg).find("h4").html();
            }

            if (IsRead > 0) {
                Badge = '<a class="badge-count"><span class="w3-badge w3-red">' + IsRead + '</span></a>';
            }

            if (IsOnline) {
                Status = '<i class="fa fa-circle green"></i>';
            }

            var code;
            var quoteText = `'${name}'`
            if (SenderId == userId) {

                code = $('<div class="box-comment" id="Div' + userId + '">' +
                    '<i class="fa fa-circle green"></i> <img class="img-circle img-sm" src="' + UserImage + '" alt="User Image" />' +
                    '<div class="comment-text">' +
                    '<span class="username" onclick="OpenPrivateChatBox(' + userId + ',' + quoteText + ')">' + '<a id="' + userId + '" class="user" >' + name + '</a> (you)' +
                    '<span class="pull-right" style="font-weight: 100;font-size: small;">' + formate(RecentMsgTime) + '</span> </span>' +
                    '<span class="RecentMsg">' + $(RecentMsg).text() + '</span></div></div>');
            }
            else {

                code = $('<div class="box-comment" id="Div' + userId + '">' + Status +
                    '<img class="img-circle img-sm" src="' + UserImage + '" alt="User Image" />' +
                    '<div class="comment-text">' +
                    '<span class="username" onclick="OpenPrivateChatBox(' + userId + ',' + quoteText + ')">' + '<a id="' + userId + '" class="user" >' + name + '</a> ' + Badge +
                    '<span class="pull-right" style="font-weight: 100;font-size: small;">' + formate(RecentMsgTime) + '</span> </span>' +
                    '<span class="RecentMsg">' + $(RecentMsg).text() +
                    '<span class="pull-right" ispin="' + IsPin + '" onclick="PinUnpinUser(' + userId + ', false, this)">' + Pinstatus + '</span></span></div></div>');
            }

            $("#divusers").append(code);
        }

        function PinUnpinUser(userId, isGroup, e) {
            var chatHub = $.connection.chatHub;
            var isPined = $(e).attr('ispin');
            var IsPin = isPined == "true" ? false : true;
            if (chatHub.connection.state == 4) {
                $.connection.hub.start().done(function () {
                    chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                    chatHub.server.pinUnpinUser($("#SenderId").val(), userId, IsPin, isGroup);
                });
            }
            else
                chatHub.server.pinUnpinUser($("#SenderId").val(), userId, IsPin, isGroup);

            if (IsPin == false) {
                $(e).attr('ispin', 'false');
                $("#Div" + userId).find(".pinstatus").attr('src', '/images/pin.png');
            } else {
                $(e).attr('ispin', 'true');
                $("#Div" + userId).find(".pinstatus").attr('src', '/images/unpin.png');
            }
        }

        function formate(date) {
            if (date) {
                if (typeof date == "string")
                    date = new Date(date);
                var day = (date.getDate() <= 9 ? "0" + date.getDate() : date.getDate());
                var month = (date.getMonth() + 1 <= 9 ? "0" + (date.getMonth() + 1) : (date.getMonth() + 1));
                var dateString = day + "-" + month + "-" + date.getFullYear();

                return dateString;
            }
            return "";
        }

        function AddMessage(userName, message, time, userimg, MessageId, IsRead, IsEdited) {

            var CurrUser = $('#SenderName').val();
            var Side = 'left';
            var TimeSide = 'right';
            var deletebtn = '';
            var editbtn = '';

            if (CurrUser == userName) {
                Side = 'right';
                TimeSide = 'left';
                deletebtn = '<a onclick="DeleteMessage(' + MessageId + ')" class="btn btn-box-tool pull-right" data-toggle="tooltip" title="Delete Message"><i class="fa fa-trash-o" ></i></a>';
                deletebtn += IsRead == true ? '<a class="btn btn-box-tool pull-right"><img class="msgstatus" src="/images/doublegreen.png" /></a>' : '<a class="btn btn-box-tool pull-right"><img class="msgstatus" src="/images/dobleblack.png" /></a>';
                editbtn = 'ondblclick="OpenEditMessage(' + MessageId + ')"';
            }

            if (IsEdited == true) {
                deletebtn += '<a class="btn btn-box-tool pull-right editstatus" data-toggle="tooltip" title="This message was edited."><i class="fa fa-pencil" aria-hidden="true"></i></a>'
            }

            var divChat = '<div class="direct-chat-msg ' + Side + '" id="Msg' + MessageId + '" ' + editbtn + '>' +
                '<div class="direct-chat-info clearfix">' +
                '<span class="direct-chat-name pull-' + Side + '">' + userName + '</span>' +
                '<span class="direct-chat-timestamp pull-' + TimeSide + '">' + time + '</span>' +
                '</div>' +
                '<img class="direct-chat-img" src="' + userimg + '" alt="Message User Image">' +
                '<div class="direct-chat-text">' + message + '</div> ' + deletebtn + '</div>';

            $('#divChatWindow').append(divChat);
        }

        function EditMessage(userName, message, time, userimg, MessageId) {
            var btn = '<a class="btn btn-box-tool pull-right editstatus" data-toggle="tooltip" title="This message was edited."><i class="fa fa-pencil" aria-hidden="true"></i></a>'
            $("#Msg" + MessageId).find(".direct-chat-text").html(message);
            var $tr = $("#Msg" + MessageId).find(".direct-chat-text");
            if ($("#Msg" + MessageId).find(".editstatus").length == 0)
                $(btn).insertAfter($tr);
        }

        function OpenEditMessage(msgid) {
            $('#EditMessage').modal('show');
            $('.EditMessageId').val(msgid);
            tinymce.get("txtEditMessage").setContent($("#Msg" + msgid).find(".direct-chat-text").html());
        }

        function DeleteMessage(msgid) {

            $.confirm({
                title: 'Cancel',
                content: 'Are you Sure You Want to Delete this Message!',
                icon: 'fa fa-warning',
                type: 'red',
                buttons: {
                    "Confirm": function () {
                        $("#Msg" + msgid).remove();

                        var toUserId = $('#ReceiverId').val();
                        var fromUserId = $('#SenderId').val();

                        var chatHub = $.connection.chatHub;
                        if (chatHub.connection.state == 4) {
                            $.connection.hub.start().done(function () {
                                chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                                if ($("#GrpId").val()) {
                                    chatHub.server.deleteGroupMessage($("#GrpId").val(), $("#GrpName").val(), fromUserId, msgid);
                                } else {
                                    chatHub.server.deleteMessage(toUserId, fromUserId, msgid);
                                }
                            });
                        }
                        else {
                            if ($("#GrpId").val()) {
                                chatHub.server.deleteGroupMessage($("#GrpId").val(), $("#GrpName").val(), fromUserId, msgid);
                            } else {
                                chatHub.server.deleteMessage(toUserId, fromUserId, msgid);
                            }
                        }
                    },
                    "Cancel": function () {
                    }
                }
            });
        }

        function OpenChatRoom(groupId, e) {
            var groupName = $(e).text();
            $('#spanUser').html("# " + groupName);
            $('#GrpId').val(groupId);
            $('#GrpName').val(groupName);

            $('#divChatWindow').html('');
            var chatHub = $.connection.chatHub;
            if (chatHub.connection.state == 4) {
                $.connection.hub.start().done(function () {
                    chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                    chatHub.server.getGroupMessage(groupId);
                });
            }
            else
                chatHub.server.getGroupMessage(groupId);
        }

        function OpenPrivateChatBox(userId, userName) {
            $('#GrpId').val('');
            $('#GrpName').val('');

            var count = parseInt($("#Div" + userId).find(".badge-count").text());
            $("#Div" + userId).find(".badge-count").each(function () {
                $(this).replaceWith('<a class="badge-count"></a>');
            });

            if (!isNaN(count)) {
                badge = badge - count;
                badge = (badge < 0) ? 0 : (badge);
                favicon.badge(badge);
            }

            $('#spanUser').html(userName);
            $('#ReceiverId').val(userId);
            $('#ReceiverName').val(userName);

            $('#divChatWindow').html('');

            var fromUserId = $('#SenderId').val();
            var chatHub = $.connection.chatHub;
            if (chatHub.connection.state == 4) {
                $.connection.hub.start().done(function () {
                    chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                    chatHub.server.getPrivateMessage(userId, fromUserId);
                });
            }
            else
                chatHub.server.getPrivateMessage(userId, fromUserId);

        }

        function changenoty(notiid) {
            var chatHub = $.connection.chatHub;
            if (chatHub.connection.state == 4) {
                $.connection.hub.start().done(function () {
                    chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                    chatHub.server.readNotification(notiid, $("#SenderId").val());
                });
            }
            else
                chatHub.server.readNotification(notiid, $("#SenderId").val());
        }

        function ParseEmoji(div) {
            var input = $(div).html();

            var output = emojione.unicodeToImage(input);

            $(div).html(output);
        }

        function uploadComplete(sender, args) {

            var imgDisplay = $get("imgDisplay");
            imgDisplay.src = "images/loading.gif";
            imgDisplay.style.cssText = "";
            var img = new Image();
            img.onload = function () {
                imgDisplay.style.cssText = "Display:none;";
                imgDisplay.src = img.src;
            };

            imgDisplay.src = "<%# ResolveUrl(UploadFolderPath) %>" + args.get_fileName();
            var chatHub = $.connection.chatHub;

            var toUserId = $('#ReceiverId').val();
            var fromUserId = $('#SenderId').val();
            var sizeKB = (args.get_length() / 1024).toFixed(2);

            var msg1;

            if (IsValidateFile(args.get_fileName())) {
                if (IsImageFile(args.get_fileName())) {
                    msg1 =
                        '<div class="box-body">' +
                        '<div class="attachment-block clearfix">' +
                        '<a><img id="imgC" style="width:100px;" class="attachment-img" src="' + imgDisplay.src + '" alt="Attachment Image"></a>' +
                        '<div class="attachment-pushed"> ' +
                        '<h4 class="attachment-heading"><i class="fa fa-image">  ' + args.get_fileName() + ' </i></h4> <br />' +
                        '<div id="at" class="attachment-text"> Dimensions : ' + imgDisplay.height + 'x' + imgDisplay.width + ', Type: ' + args.get_contentType() +

                        '</div>' +
                        '</div>' +
                        '</div>' +
                        '<a id="btnDownload" href="' + imgDisplay.src + '" class="btn btn-default btn-xs" download="' + args.get_fileName() + '"><i class="fa fa fa-download"></i> Download</a>' +
                        '<button type="button" id="ShowModelImg"  value="' + imgDisplay.src + '"  class="btn btn-default btn-xs"><i class="fa fa-camera"></i> View</button>' +
                        '<span class="pull-right text-muted">File Size : ' + sizeKB + ' Kb</span>' +
                        '</div>';
                }
                else {

                    msg1 =
                        '<div class="box-body">' +
                        '<div class="attachment-block clearfix">' +
                        '<a><img id="imgC" style="width:100px;" class="attachment-img" src="images/file-icon.png" alt="Attachment Image"></a>' +
                        '<div class="attachment-pushed"> ' +
                        '<h4 class="attachment-heading"><i class="fa fa-file-o">  ' + args.get_fileName() + ' </i></h4> <br />' +
                        '<div id="at" class="attachment-text"> Type: ' + args.get_contentType() +

                        '</div>' +
                        '</div>' +
                        '</div>' +
                        '<a id="btnDownload" href="' + imgDisplay.src + '" class="btn btn-default btn-xs" download="' + args.get_fileName() + '"><i class="fa fa fa-download"></i> Download</a>' +
                        '<a href="' + imgDisplay.src + '" target="_blank" class="btn btn-default btn-xs"><i class="fa fa-camera"></i> View</a>' +
                        '<span class="pull-right text-muted">File Size : ' + sizeKB + ' Kb</span>' +
                        '</div>';
                }
                if (chatHub.connection.state == 4) {
                    $.connection.hub.start().done(function () {
                        chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                        if ($("#GrpId").val()) {
                            chatHub.server.sendGroupMessage($("#GrpId").val(), $("#GrpName").val(), fromUserId, msg1);
                        } else {
                            chatHub.server.sendPrivateMessage(toUserId, fromUserId, msg1);
                        }
                    });
                }
                else {
                    if ($("#GrpId").val()) {
                        chatHub.server.sendGroupMessage($("#GrpId").val(), $("#GrpName").val(), fromUserId, msg1);
                    } else {
                        chatHub.server.sendPrivateMessage(toUserId, fromUserId, msg1);
                    }
                }
            }

            imgDisplay.src = '';
        }

        function EdituploadComplete(sender, args) {
            var imgDisplay = $get("imgDisplay");
            imgDisplay.src = "images/loading.gif";
            imgDisplay.style.cssText = "";
            var img = new Image();
            img.onload = function () {
                imgDisplay.style.cssText = "Display:none;";
                imgDisplay.src = img.src;
            };

            imgDisplay.src = "<%# ResolveUrl(UploadFolderPath) %>" + args.get_fileName();
            var chatHub = $.connection.chatHub;

            var MessageId = $(".EditMessageId").val();
            var toUserId = $('#ReceiverId').val();
            var fromUserId = $('#SenderId').val();
            var sizeKB = (args.get_length() / 1024).toFixed(2);

            var msg1;

            if (IsValidateFile(args.get_fileName())) {
                if (IsImageFile(args.get_fileName())) {
                    msg1 =
                        '<div class="box-body">' +
                        '<div class="attachment-block clearfix">' +
                        '<a><img id="imgC" style="width:100px;" class="attachment-img" src="' + imgDisplay.src + '" alt="Attachment Image"></a>' +
                        '<div class="attachment-pushed"> ' +
                        '<h4 class="attachment-heading"><i class="fa fa-image">  ' + args.get_fileName() + ' </i></h4> <br />' +
                        '<div id="at" class="attachment-text"> Dimensions : ' + imgDisplay.height + 'x' + imgDisplay.width + ', Type: ' + args.get_contentType() +

                        '</div>' +
                        '</div>' +
                        '</div>' +
                        '<a id="btnDownload" href="' + imgDisplay.src + '" class="btn btn-default btn-xs" download="' + args.get_fileName() + '"><i class="fa fa fa-download"></i> Download</a>' +
                        '<button type="button" id="ShowModelImg"  value="' + imgDisplay.src + '"  class="btn btn-default btn-xs"><i class="fa fa-camera"></i> View</button>' +
                        '<span class="pull-right text-muted">File Size : ' + sizeKB + ' Kb</span>' +
                        '</div>';
                }
                else {

                    msg1 =
                        '<div class="box-body">' +
                        '<div class="attachment-block clearfix">' +
                        '<a><img id="imgC" style="width:100px;" class="attachment-img" src="images/file-icon.png" alt="Attachment Image"></a>' +
                        '<div class="attachment-pushed"> ' +
                        '<h4 class="attachment-heading"><i class="fa fa-file-o">  ' + args.get_fileName() + ' </i></h4> <br />' +
                        '<div id="at" class="attachment-text"> Type: ' + args.get_contentType() +

                        '</div>' +
                        '</div>' +
                        '</div>' +
                        '<a id="btnDownload" href="' + imgDisplay.src + '" class="btn btn-default btn-xs" download="' + args.get_fileName() + '"><i class="fa fa fa-download"></i> Download</a>' +
                        '<a href="' + imgDisplay.src + '" target="_blank" class="btn btn-default btn-xs"><i class="fa fa-camera"></i> View</a>' +
                        '<span class="pull-right text-muted">File Size : ' + sizeKB + ' Kb</span>' +
                        '</div>';
                }
                if (chatHub.connection.state == 4) {
                    $.connection.hub.start().done(function () {
                        chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                        if ($("#GrpId").val()) {
                            chatHub.server.editGroupMessage($("#GrpId").val(), $("#GrpName").val(), fromUserId, msg1, MessageId);
                        } else {
                            chatHub.server.editMessage(toUserId, fromUserId, msg1, MessageId);
                        }
                    });
                }
                else {
                    if ($("#GrpId").val()) {
                        chatHub.server.editGroupMessage($("#GrpId").val(), $("#GrpName").val(), fromUserId, msg1, MessageId);
                    } else {
                        chatHub.server.editMessage(toUserId, fromUserId, msg1, MessageId);
                    }
                }
            }

            imgDisplay.src = '';
            $("#txtEditMessage").val('');
            $(".emojionearea-editor").html('');
            $('#EditMessage').modal('hide');
        }

        function uploadStarted() {
            $get("imgDisplay").style.display = "none";
        }

        $(document).on('click', '#ShowModelImg', function () {
            $get("ImgModal").src = this.value;
            $('#ShowPictureModal').modal('show');
        });

        function IsValidateFile(fileF) {
            var allowedFiles = ["doc", "docx", "pdf", "txt", "xlsx", "xls", "png", "jpg", "gif"];
            var ext = fileF.split('.').pop().toLowerCase();
            if ($.inArray(ext, allowedFiles) == -1) {
                alert("Please upload files having extensions: " + allowedFiles.join(', ') + " only.");
                return false;
            }
            return true;
        }

        function IsImageFile(fileF) {
            var ImageFiles = ["png", "jpg", "gif"];
            var ext = fileF.split('.').pop().toLowerCase();
            if ($.inArray(ext, ImageFiles) == -1) {
                return false;
            }
            return true;
        }

        function PlaySound() {
            var audio = new Audio('/sounds/sound.wav');
            audio.play();
        }

        function DesktopNotification(bodymsg) {
            var url = window.location.origin + '/Chat.aspx';

            if (!("Notification" in window)) {
                console.log("This browser does not support desktop notification");
            }
            else if (Notification.permission === "granted") {
                var notification = new Notification("Chat App", {
                    icon: 'images/end-chat.png',
                    body: bodymsg
                });

                notification.onclick = function () {
                    window.open(url);
                };

                /* Callback function when the notification is closed. */
                notification.onclose = function () {
                    console.log('Notification closed');
                };
            }
            else if (Notification.permission !== 'denied') {
                Notification.requestPermission(function (permission) {
                    if (!('permission' in Notification)) {
                        Notification.permission = permission;
                    }
                    if (permission === "granted") {
                        var notification = new Notification("Chat App", {
                            icon: 'images/end-chat.png',
                            body: bodymsg
                        });

                        notification.onclick = function () {
                            window.open(url);
                        };

                        /* Callback function when the notification is closed. */
                        notification.onclose = function () {
                            console.log('Notification closed');
                        };
                    }
                });
            }
        }

        function OpenGroup() {
            $('#AddGroup').modal('show');
            $("#AddGroup").find(".modal-title").html("Add Group");
            $('#UserList').html('');
            $("#GroupName").val('');
            $("#GroupId").val(0);

            $.ajax({
                type: "POST",
                url: "Chat.aspx/GetAllUsers",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    $.each(response.d, function (index, emp) {
                        if ($("#SenderId").val() != emp.UserId) {
                            var User = '<div class="col-md-4">' +
                                '<div class="form-check">' +
                                '<input type="checkbox" class="form-check-input" value="' + emp.UserId + '" name="SelectedUsers">' +
                                '<label class="form-check-label" for="Users" style="margin-left: 5px;"> ' + emp.UserName + '</label>' +
                                '</div>' +
                                '</div >';

                            $('#UserList').append(User);
                        }
                    });
                }
            });
        }

        function OpenEditGroup(groupId) {
            $('#AddGroup').modal('show');
            $("#AddGroup").find(".modal-title").html("Edit Group");
            $('#UserList').html('');

            $.ajax({
                type: "POST",
                url: "Chat.aspx/GetGroup",
                data: '{GroupId: "' + groupId + '" }',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (response) {
                    $.each(response.d.AllUsers, function (index, emp) {
                        if ($("#SenderId").val() != emp.UserId) {

                            var User = '';
                            if (emp.Selected) {
                                User = '<div class="col-md-4">' +
                                    '<div class="form-check">' +
                                    '<input type="checkbox" class="form-check-input" value="' + emp.UserId + '" name="SelectedUsers" checked>' +
                                    '<label class="form-check-label" for="Users" style="margin-left: 5px;"> ' + emp.UserName + '</label>' +
                                    '</div>' +
                                    '</div >';
                            } else {
                                User = '<div class="col-md-4">' +
                                    '<div class="form-check">' +
                                    '<input type="checkbox" class="form-check-input" value="' + emp.UserId + '" name="SelectedUsers">' +
                                    '<label class="form-check-label" for="Users" style="margin-left: 5px;"> ' + emp.UserName + '</label>' +
                                    '</div>' +
                                    '</div >';
                            }


                            $('#UserList').append(User);
                        }
                    });

                    $("#GroupName").val(response.d.Group.GroupName);
                    $("#GroupId").val(response.d.Group.ID);
                }
            });
        }

        function SaveGroup() {

            var chatHub = $.connection.chatHub;
            var SelectedUsers = [];
            SelectedUsers.push($("#SenderId").val());
            $.each($("input[name='SelectedUsers']:checked"), function () {
                SelectedUsers.push($(this).val());
            });
            if (!$("#GroupName").val()) {
                $.alert({
                    title: 'Group',
                    content: 'Please enter Group name.',
                    icon: 'fa fa-warning',
                    type: 'red',
                });
                return;
            }

            var data = { ID: $("#GroupId").val(), GroupName: $("#GroupName").val(), UserIds: SelectedUsers.join(","), CreatedBy: $("#SenderId").val() };

            $.ajax({
                type: "POST",
                url: "Chat.aspx/SaveGroup",
                data: '{model: ' + JSON.stringify(data) + '}',
                contentType: 'application/json',
                dataType: "json",
                success: function (response) {
                    if (response.d == 0) {
                        $.alert({
                            title: 'Group',
                            content: 'Group Saved Successfully.',
                            icon: 'fa fa-success',
                            type: 'green',
                        });
                        $('#AddGroup').modal('hide');

                        if (chatHub.connection.state == 4) {
                            $.connection.hub.start().done(function () {
                                chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                                if ($("#GroupId").val() > 0) {
                                    chatHub.server.editGroup($("#GroupName").val(), SelectedUsers.join(","));
                                }
                                else {
                                    chatHub.server.addToGroup($("#GroupName").val(), SelectedUsers.join(","));
                                }
                            });
                        }
                        else {
                            if ($("#GroupId").val() > 0) {
                                chatHub.server.editGroup($("#GroupName").val(), SelectedUsers.join(","));
                            }
                            else {
                                chatHub.server.addToGroup($("#GroupName").val(), SelectedUsers.join(","));
                            }
                        }
                    } else if (response.d == 1) {
                        $.alert({
                            title: 'Group',
                            content: 'Group Name already exist.',
                            icon: 'fa fa-warning',
                            type: 'red',
                        });
                    } else {
                        $.alert({
                            title: 'Group',
                            content: 'Something went wrong, Please try after some time.',
                            icon: 'fa fa-warning',
                            type: 'red',
                        });
                    }
                }
            });
        }

        function DeleteGroup(groupId) {
            $.confirm({
                title: 'Cancel',
                content: 'Are you Sure You Want to Delete this Group!',
                icon: 'fa fa-warning',
                type: 'red',
                buttons: {
                    "Confirm": function () {
                        $("#Grp" + groupId).remove();

                        var chatHub = $.connection.chatHub;
                        if (chatHub.connection.state == 4) {
                            $.connection.hub.start().done(function () {
                                chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                                chatHub.server.deleteGroup(groupId);
                            });
                        }
                        else {
                            chatHub.server.deleteGroup(groupId);
                        }
                    },
                    "Cancel": function () {
                    }
                }
            });
        }

        function SearchChat() {
            var SearchString = $("#SearchString").val();
            var chatHub = $.connection.chatHub;
            $('#divChatWindow').html('');
            var toUserId = $('#ReceiverId').val();
            var fromUserId = $('#SenderId').val();

            if (SearchString.length > 0) {
                if (chatHub.connection.state == 4) {
                    $.connection.hub.start().done(function () {
                        chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                        if ($("#GrpId").val()) {
                            chatHub.server.groupSearch($("#GrpId").val(), SearchString);
                        } else {
                            chatHub.server.privateRoomSearch(toUserId, fromUserId, SearchString);
                        }
                    });
                }
                else {
                    if ($("#GrpId").val()) {
                        chatHub.server.groupSearch($("#GrpId").val(), SearchString);
                    } else {
                        chatHub.server.privateRoomSearch(toUserId, fromUserId, SearchString);
                    }
                }
            } else {
                if ($("#GrpId").val()) {
                    chatHub.server.getGroupMessage($("#GrpId").val());
                } else {
                    chatHub.server.getPrivateMessage(toUserId, fromUserId);
                }
            }
        }

        function myFunction() {
            var input, filter, ul, li, a, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            ul = document.getElementsByClassName("box-comment");
            for (i = 0; i < ul.length; i++) {
                a = ul[i].getElementsByTagName("a")[0];
                txtValue = a.textContent || a.innerText;
                if (txtValue.toUpperCase().indexOf(filter) > -1) {
                    ul[i].style.display = "";
                } else {
                    ul[i].style.display = "none";
                }
            }
        }

        function GetUsers(e) {
            var selection = $(e).val();

            var chatHub = $.connection.chatHub;
            if (chatHub.connection.state == 4) {
                $.connection.hub.start().done(function () {
                    chatHub.server.reConnect($("#SenderId").val(), $("#SenderName").val());
                    chatHub.server.getUsers(selection, $("#SenderId").val());
                });
            }
            else {
                chatHub.server.getUsers(selection, $("#SenderId").val());
            }
        }
    </script>

</head>
<body>

    <form id="form1" class="form-horizontal" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
        <div class="content-wrapper container">

            <div class="row">

                <div class="col-md-8">
                    <!-- DIRECT CHAT PRIMARY -->
                    <div class="box box-primary direct-chat direct-chat-primary">
                        <div class="box-header with-border">
                            <h3 class="box-title" style="color: dimgrey;">Discussion Room <span id='spanUser'></span></h3>
                            <div class="search-container pull-right">
                                <input type="text" id="SearchString" onkeyup="SearchChat()" placeholder="Search this conversation" />
                            </div>
                        </div>
                        <!-- /.box-header -->
                        <div class="box-body">
                            <!-- Conversations are loaded here -->
                            <div class="box-body" id="chat-box">
                                <!-- Conversations are loaded here -->

                                <div id="divChatWindow" class="direct-chat-messages" style="height: 400px; overflow: scroll;">
                                </div>
                            </div>

                        </div>
                        <!-- /.box-body -->
                        <div class="box-footer">
                            <div class="input-group">
                                <textarea id="txtMessage" class="form-control" rows="3" style="resize: none"></textarea>
                                <div class="input-group-btn">
                                    <button type="button" class="btn btn-primary btn-flat" id="btnSendMsg" value="send"><i class="glyphicon glyphicon-send"></i></button>
                                    <asp:UpdatePanel ID="UpdatePanel2" runat="server">
                                        <ContentTemplate>
                                            <span class="upload-btn-wrapper">
                                                <button id="btnFile" class="btn btn-default btn-flat"><i class="glyphicon glyphicon-paperclip"></i></button>
                                                <ajaxToolkit:AsyncFileUpload OnClientUploadComplete="uploadComplete" runat="server" ID="AsyncFileUpload1"
                                                    ThrobberID="imgLoader" OnUploadedComplete="FileUploadComplete" OnClientUploadStarted="uploadStarted" />
                                            </span>
                                        </ContentTemplate>
                                    </asp:UpdatePanel>
                                </div>
                            </div>

                            <img id="imgDisplay" src="" class="user-image" style="height: 100px;" />
                        </div>
                        <!-- /.box-footer-->
                    </div>
                    <!--/.direct-chat -->
                </div>
                <!-- /.col -->
                <div class="col-md-4">

                    <div class="box box-solid box-primary">

                        <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Search for names.." title="Type in a name" />

                        <select id="selection" onchange="GetUsers(this)">
                            <option value="1">All</option>
                            <option value="2">Recent</option>
                            <option value="3">Online</option>
                        </select>

                        <div class="box-header with-border">
                            <h3 class="box-title">Users <span id='UserCount'></span></h3>
                        </div>

                        <div class="box-footer box-comments" id="divusers">
                        </div>

                        <%--</div>

                    <div class="box box-solid box-primary">--%>

                        <div class="box-header with-border">
                            <h3 class="box-title">Groups </h3>
                            <a class="btn btn-box-tool pull-right" onclick="OpenGroup()"><i class="fa fa-plus"></i></a>
                        </div>

                        <div class="box-footer box-comments" id="divgroups">
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <span id="time"></span>
        <input id="SenderId" type="hidden" />
        <input id="SenderName" type="hidden" />
        <input id="ReceiverId" type="hidden" />
        <input id="ReceiverName" type="hidden" />
        <input id="GrpId" type="hidden" />
        <input id="GrpName" type="hidden" />

        <div class="modal fade" id="ShowPictureModal" role="dialog">
            <div class="modal-dialog" style="width: 100%; max-width: 750px; min-width: 350px">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="container">
                            <img id="ImgModal" src="Uploads/Chrysanthemum.jpg" class="user-image" style="max-width: 700px; min-width: 300px" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="EditMessage" role="dialog">
            <div class="modal-dialog" style="width: 700px">
                <div class="modal-content">
                    <div class="modal-header bg-light-blue-gradient with-border">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Edit Message</h4>
                    </div>
                    <div class="modal-body">
                        <div class="container">
                            <input type="hidden" class="EditMessageId" />
                            <div class="input-group" style="width: 650px;">
                                <textarea id="txtEditMessage" class="form-control" rows="3" style="resize: none"></textarea>
                                <div class="input-group-btn">
                                    <%--<div class="btn-group">--%>
                                    <button type="button" class="btn btn-primary btn-flat" id="btnEditSendMsg" value="send"><i class="glyphicon glyphicon-send"></i></button>
                                    <asp:UpdatePanel ID="UpdatePanel3" runat="server">
                                        <ContentTemplate>
                                            <span class="upload-btn-wrapper">
                                                <button id="btnEditFile" class="btn btn-default btn-flat"><i class="glyphicon glyphicon-paperclip"></i></button>
                                                <ajaxToolkit:AsyncFileUpload OnClientUploadComplete="EdituploadComplete" runat="server" ID="AsyncFileUpload2"
                                                    ThrobberID="imgLoader" OnUploadedComplete="EditFileUploadComplete" OnClientUploadStarted="uploadStarted" />
                                            </span>
                                        </ContentTemplate>
                                    </asp:UpdatePanel>
                                    <%--</div>--%>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="AddGroup" role="dialog">
            <div class="modal-dialog" style="width: 700px">
                <div class="modal-content">
                    <div class="modal-header bg-light-blue-gradient with-border">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Add Group</h4>
                    </div>
                    <div class="modal-body">
                        <div class="container">
                            <input type="hidden" id="GroupId" value="0" />
                            <div class="row">
                                <div class="col-md-4">
                                    <label for="GroupName">Group Name</label>
                                    <input type="text" class="form-control" name="GroupName" id="GroupName" aria-describedby="emailHelp" placeholder="Group Name" />
                                </div>
                            </div>
                            <br />
                            <div class="row col-md-12">
                                <label for="User">
                                    Add Users
                                </label>
                                <br />
                                <div class="row" id="UserList" style="width: 700px;">
                                    <!-- List users here -->
                                </div>
                            </div>
                            <br />
                            <div class="row col-md-offset-6">
                                <button type="button" class="btn btn-primary" onclick="SaveGroup()" id="btnAddGroup">Submit</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <style>
            .upload-btn-wrapper {
                position: relative;
                overflow: hidden;
                display: inline-block;
                margin-top: 5px;
            }

                .upload-btn-wrapper input[type=file] {
                    font-size: 100px;
                    position: absolute;
                    left: 0;
                    top: 0;
                    opacity: 0;
                }

            .direct-chat-text img {
                width: 500px;
                cursor: pointer;
            }
        </style>

        <script src="Scripts/bootstrap.min.js"></script>
        <script src="Scripts/jquery-confirm.min.js"></script>
        <script>
            $('#divChatWindow').on('click', '.direct-chat-text img', function () {
                $get("ImgModal").src = $(this).attr('src');
                $('#ShowPictureModal').modal('show');
            });
        </script>
    </form>
</body>
</html>
